project_id = "nklvygubbhxolkjxgpxl"

[functions.ai-tutor]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.translate-text]
verify_jwt = false
